export interface InformationCardImage {
  url: string
  /** Photographer / rights holder as credited on Wikimedia Commons. */
  credit: string
  license: string
  /** Commons file page: the licence and attribution record for this image. */
  source: string
}

// One unique, subject-matched photo per Information Hub card, keyed by card id. All images are
// freely licensed Wikimedia Commons originals served as 1920px CDN thumbnails (verified reachable,
// >=1600px wide); CC BY / BY-SA licences require the credit line the card renders.
export const informationCardImages: Record<string, InformationCardImage> = {
  "iran-war-forestry-timeline": { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Solomon_Sea_%28oil_tanker%29%2C_in_the_Solent%2C_England.jpg/1920px-Solomon_Sea_%28oil_tanker%29%2C_in_the_Solent%2C_England.jpg", credit: "ITookSomePhotos", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Solomon_Sea_(oil_tanker),_in_the_Solent,_England.jpg" },
  "kenya-forest-regulator": { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Karura_Forest-Nairobi.jpg/1920px-Karura_Forest-Nairobi.jpg", credit: "Queen Asali", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Karura_Forest-Nairobi.jpg" },
  "kenya-rules-pipeline": { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Kenyatta_International_Convention_Centre%2C_Nairobi%2C_by_Karl_Henrik_N%C3%B8stvik_architect%2C_general.jpg/1920px-Kenyatta_International_Convention_Centre%2C_Nairobi%2C_by_Karl_Henrik_N%C3%B8stvik_architect%2C_general.jpg", credit: "IndicibleEspace", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Kenyatta_International_Convention_Centre,_Nairobi,_by_Karl_Henrik_N%C3%B8stvik_architect,_general.jpg" },
  "east-africa-fuel-corridor": { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Shell_Tanker_Truck_at_a_Fuel_Station_in_Capiov%C3%AD%2C_Argentina.jpg/1920px-Shell_Tanker_Truck_at_a_Fuel_Station_in_Capiov%C3%AD%2C_Argentina.jpg", credit: "Horacio Cambeiro", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Shell_Tanker_Truck_at_a_Fuel_Station_in_Capiov%C3%AD,_Argentina.jpg" },
  "fertiliser-supply-shock": { url: "https://upload.wikimedia.org/wikipedia/commons/4/48/Spreading_fertilizer_-_geograph.org.uk_-_5379965.jpg", credit: "Russel Wills", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Spreading_fertilizer_-_geograph.org.uk_-_5379965.jpg" },
  "kenya-dryland-policy": { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Tsavo_West%2C_Kenya_%2853342923288%29.jpg/1920px-Tsavo_West%2C_Kenya_%2853342923288%29.jpg", credit: "Nina R from Africa", license: "CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Tsavo_West,_Kenya_(53342923288).jpg" },
  "oromia-isfl-issuance": { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Bale_Mountains_National_Park_%2849851231126%29.jpg/1920px-Bale_Mountains_National_Park_%2849851231126%29.jpg", credit: "Nina R from Africa", license: "CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Bale_Mountains_National_Park_(49851231126).jpg" },
  "kenya-carbon-rulebook": { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Kasigau197.JPG/1920px-Kasigau197.JPG", credit: "Ina96", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Kasigau197.JPG" },
  "ethiopia-carbon-directive": { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/May_Be%27ati_church_forest.jpg/1920px-May_Be%27ati_church_forest.jpg", credit: "Jan Nyssen", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:May_Be%27ati_church_forest.jpg" },
  "kenya-carbon-registry": { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Aberdare_range.jpg/1920px-Aberdare_range.jpg", credit: "Tony0991", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Aberdare_range.jpg" },
  "uganda-timber-prices": { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Young_female_carpenter_01.jpg/1920px-Young_female_carpenter_01.jpg", credit: "Shona Kobuyambi", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Young_female_carpenter_01.jpg" },
  "tropical-timber-benchmark": { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Stacked_Timber_Displaying_Growth_Rings.jpg/1920px-Stacked_Timber_Displaying_Growth_Rings.jpg", credit: "Kelsey Todd", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Stacked_Timber_Displaying_Growth_Rings.jpg" },
  "article-six-pipeline": { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Rachel_the_tireless_tree_planter%2C_Kenya_photo_2.jpg/1920px-Rachel_the_tireless_tree_planter%2C_Kenya_photo_2.jpg", credit: "Caroletravis", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Rachel_the_tireless_tree_planter,_Kenya_photo_2.jpg" },
  "nfc-investment": { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Pine_Plantation_Trail_4227.jpg/1920px-Pine_Plantation_Trail_4227.jpg", credit: "Chris Light", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Pine_Plantation_Trail_4227.jpg" },
  "nfc-guarantee": { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Eucalyptus_trees_Plantation_on_a_Hill_Along_Kabale-Mbarara_Highway.jpg/1920px-Eucalyptus_trees_Plantation_on_a_Hill_Along_Kabale-Mbarara_Highway.jpg", credit: "Emma Oruk", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Eucalyptus_trees_Plantation_on_a_Hill_Along_Kabale-Mbarara_Highway.jpg" },
  "nfc-expansion-pipeline": { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Agro-Forestry_Plantation-1.jpg/1920px-Agro-Forestry_Plantation-1.jpg", credit: "S.K. Gawali", license: "CC0", source: "https://commons.wikimedia.org/wiki/File:Agro-Forestry_Plantation-1.jpg" },
  "cafi-sme-facility": { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Rainforest_-_Ituri_%2820874628148%29.jpg/1920px-Rainforest_-_Ituri_%2820874628148%29.jpg", credit: "MONUSCO Photos", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Rainforest_-_Ituri_(20874628148).jpg" },
  "kenya-commercial-strategy": { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Forest_Plantation_%28173585991%29.jpeg/1920px-Forest_Plantation_%28173585991%29.jpeg", credit: "Alexandre Ultré", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Forest_Plantation_(173585991).jpeg" },
  "forestry-concession-rules": { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Grumier_dans_les_rues_de_Douala.jpg/1920px-Grumier_dans_les_rues_de_Douala.jpg", credit: "Happiraphael", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Grumier_dans_les_rues_de_Douala.jpg" },
  "kenya-seed-regulation": { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Tree_Seeds_%28132208595%29.jpeg/1920px-Tree_Seeds_%28132208595%29.jpeg", credit: "Lukas B", license: "CC0", source: "https://commons.wikimedia.org/wiki/File:Tree_Seeds_(132208595).jpeg" },
  "kenya-rwanda-seed-policy": { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Buhanga_ECO-Park.jpg/1920px-Buhanga_ECO-Park.jpg", credit: "Muhirehussein12", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Buhanga_ECO-Park.jpg" },
  "tree-genebank": { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Seedbank.jpg/1920px-Seedbank.jpg", credit: "R. C. Johnson", license: "CC BY 2.5", source: "https://commons.wikimedia.org/wiki/File:Seedbank.jpg" },
  "rwanda-coffee-genetics": { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Coffee_cherries_of_varying_ripeness%2C_on_a_tree_in_Colombia_%28by_Brian_Smith%29.jpg/1920px-Coffee_cherries_of_varying_ripeness%2C_on_a_tree_in_Colombia_%28by_Brian_Smith%29.jpg", credit: "U. S. Fish and Wildlife Service - Northeast Region", license: "Public domain", source: "https://commons.wikimedia.org/wiki/File:Coffee_cherries_of_varying_ripeness,_on_a_tree_in_Colombia_(by_Brian_Smith).jpg" },
  "quality-tree-seed-project": { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Skukuza_indigenous_nursery%2C_Kruger_National_Park%2C_South_Africa_%2814987235125%29.jpg/1920px-Skukuza_indigenous_nursery%2C_Kruger_National_Park%2C_South_Africa_%2814987235125%29.jpg", credit: "flowcomm", license: "CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Skukuza_indigenous_nursery,_Kruger_National_Park,_South_Africa_(14987235125).jpg" },
  "commercial-breeding-plan": { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Eucalyptus_plantation_in_final_stages.JPG/1920px-Eucalyptus_plantation_in_final_stages.JPG", credit: "Balaji Kasirajan", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Eucalyptus_plantation_in_final_stages.JPG" },
  "uganda-lidar-inventory": { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/20240501-FS-RB-Ketchikan-Road-0001_%2854091445285%29.jpg/1920px-20240501-FS-RB-Ketchikan-Road-0001_%2854091445285%29.jpg", credit: "Forest Service Alaska Region, USDA", license: "Public domain", source: "https://commons.wikimedia.org/wiki/File:20240501-FS-RB-Ketchikan-Road-0001_(54091445285).jpg" },
  "open-foris-uganda": { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Whitebark_pine_tree_monitoring-_measuring_the_diameter_at_breast_height_%28DBH%29_%2853041974954%29.jpg/1920px-Whitebark_pine_tree_monitoring-_measuring_the_diameter_at_breast_height_%28DBH%29_%2853041974954%29.jpg", credit: "YellowstoneNPS", license: "Public domain", source: "https://commons.wikimedia.org/wiki/File:Whitebark_pine_tree_monitoring-_measuring_the_diameter_at_breast_height_(DBH)_(53041974954).jpg" },
  "tree-crop-mapping-guidance": { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Tea_farming_in_Kericho_03.JPG/1920px-Tea_farming_in_Kericho_03.JPG", credit: "Ahero dala", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Tea_farming_in_Kericho_03.JPG" },
  "miti360-dataset": { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Mount_Suswa%2C_Kenya_%2831407356342%29.jpg/1920px-Mount_Suswa%2C_Kenya_%2831407356342%29.jpg", credit: "Nina R from Africa", license: "CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Mount_Suswa,_Kenya_(31407356342).jpg" },
  "tanzania-processing-study": { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Making_square_lumber_11.jpg/1920px-Making_square_lumber_11.jpg", credit: "Kambai Akau", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Making_square_lumber_11.jpg" },
  "safari-ya-mbao": { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Men_put_timbers_on_lorry.jpg/1920px-Men_put_timbers_on_lorry.jpg", credit: "KelvinJM", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Men_put_timbers_on_lorry.jpg" },
  "sepal-toolkit": { url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/2026-01-01%2C_Cubat%C3%A3o%2C_satellite_image_%28Sentinel-2%29.jpg/1920px-2026-01-01%2C_Cubat%C3%A3o%2C_satellite_image_%28Sentinel-2%29.jpg", credit: "European Space Agency", license: "CC BY-SA 3.0 igo", source: "https://commons.wikimedia.org/wiki/File:2026-01-01,_Cubat%C3%A3o,_satellite_image_(Sentinel-2).jpg" },
}
