/**
 * Asset Intelligence reality reset (Track v5). This file used to generate
 * an entirely fabricated forestry simulation (seeded pseudo-random growth
 * curves, fake species/DBH/height distributions, fake contractors,
 * invoices and a fake multi-year portfolio-value walk) for the three real
 * reference assets. That entire simulation engine has been removed.
 *
 * Every number reachable from this file now traces to
 * vite-version/src/app/dashboard/data/asset-state-v1.json, generated by
 * backend/scripts/asset_state_model.py -- which reuses the SAME validated
 * hierarchical Monte Carlo engine built for the Zurkt/Evergreen supply
 * case, not a second model. See asset-intelligence-data.ts for the typed
 * AssetState this file is built on top of.
 *
 * `AssetSubBlock` below is now a DERIVED ANALYSIS ZONE (Track v5-4): an
 * illustrative area-weighted split of the asset's real modelled
 * material-class mixture, NOT a surveyed compartment plan. It carries a
 * material class and a real probability -- never a fabricated species,
 * age, DBH, height, contractor, or activity.
 */
import {
  assetStates,
  deriveAnalysisZones,
  formatMaterialClassLabel,
  getAssetStateByEntityId,
  MATERIAL_CLASS_COLORS,
  type AssetState,
  type DerivedAnalysisZone,
} from "./asset-intelligence-data"

export type TreeVariety = string // now a material-class key (e.g. "eucalyptus_plantation") -- see MATERIAL_CLASS_COLORS
export type Country = "Uganda" | "Kenya" | "Tanzania"

export type AssetGeometryTier = "canonical_polygon" | "source_verified_polygon"

export type CanonicalEntityIdentity = {
  entityId: string
  entityType: string
  canonicalName: string
  worldId: string
  geometryObservationId: string
  geometryObservationMethod: string
  aoiId: string
  aoiVersionId: string
  cohortKeys: string[]
  operationalDatabase: string
  confirmedAt: string
}

export type AssetEvidenceProvenance = {
  geometryTier: AssetGeometryTier
  geometryLabel: string
  geometryNote: string
  canonicalIdentity: CanonicalEntityIdentity
  compartmentsNote: string
}

/** A DERIVED ANALYSIS ZONE -- real modelled material-class share, not a surveyed compartment. */
export type AssetSubBlock = {
  id: string
  subBlock: string
  variety: TreeVariety
  size: number
  plantedSize: number
  /** Real probability (0-100) of this material class within the asset, NOT an age in years. */
  age: number
}

export type AssetGroup = {
  id: string
  block: string
  summaryTitle: string
  summaryDescription: string
  location: string
  country: Country
  mapCenter: [number, number]
  provenance: AssetEvidenceProvenance
  subBlocks: AssetSubBlock[]
  /** The real AssetState this group is built from -- consult directly for anything beyond map layout. */
  assetState: AssetState
}

export type SubBlock = AssetSubBlock

export type DerivedAreaMetrics = {
  totalTrees: number
  estimatedVolume: number
  estimatedTonnage: number
  estimatedValuation: number
  investmentPlaced: number
  averageHeight: number
  averageDbh: number
  survivalRate: number
  expectedPricePerTonne: number
  expectedPricePerM3: number
}

export type SpeciesAllocationDatum = {
  category: TreeVariety
  value: number
  amount: number
  fill: string
}

export const dashboardCurrentYear = 2026
const WOOD_DENSITY_T_PER_M3 = 0.55

/**
 * Real provenance/identity for the three reference assets, confirmed
 * 2026-09-11 against ea_forests_uganda_country_pass. See
 * docs/architecture/CANONICAL_DATABASE_RUNTIME.md.
 */
const REFERENCE_ASSET_IDENTITY: Record<string, { block: string; summaryTitle: string; summaryDescription: string; location: string; country: Country; mapCenter: [number, number]; provenance: AssetEvidenceProvenance }> = {
  "c7151c94-2797-4dd8-b6c3-b9aea8dda81e": {
    block: "Kampimpini",
    summaryTitle: "Kampimpini reference case",
    summaryDescription:
      "One of EA Forests' three gold-standard Asset Intelligence reference cases. canonical_name = \"Kapimpini\" (the real, gazetted Central Forest Reserve in Nakaseke District, National Forestry Authority, designated 1967); display_name/alias = \"Kampimpini\". Every operational/forestry number below is now real model output (asset-state-v1.json), not a demo simulation.",
    location: "Nakaseke, Central",
    country: "Uganda",
    mapCenter: [0.98736, 32.07765],
    provenance: {
      geometryTier: "canonical_polygon",
      geometryLabel: "Canonical CFR polygon",
      geometryNote:
        "Uganda CFR boundary spine, reconciliation status POLYGON_LINKED, source record \"Kapimpini\". Canonical AOI polygon area 6,078.12 ha (repo boundary export reports 6,120.9 ha; NFA/public reporting ~6,068 ha; designated 1967). geometry_method \"repository_derived\" -- no recoverable original KML/GeoJSON artifact was found, so this is a real polygon of unverified original lineage, not a surveyed boundary.",
      canonicalIdentity: {
        entityId: "c7151c94-2797-4dd8-b6c3-b9aea8dda81e",
        entityType: "reserve",
        canonicalName: "Kapimpini",
        worldId: "b407cc28-f235-4c1d-bc5b-058357cb2dd4",
        geometryObservationId: "0564dee6-1ac7-408e-951e-f1b7050d55b3",
        geometryObservationMethod: "repository_derived",
        aoiId: "1215d267-cc08-40c3-9755-96959c0fdeb0",
        aoiVersionId: "b8b1656c-4015-41a1-a907-f9866a94dc1e",
        cohortKeys: ["uganda-cfr-observation-cohort"],
        operationalDatabase: "ea_forests_uganda_country_pass",
        confirmedAt: "2026-09-11",
      },
      compartmentsNote: "DERIVED ANALYSIS ZONES -- an illustrative area split of the real modelled material-class mixture, not a surveyed compartment plan.",
    },
  },
  "953552e7-6c06-4e9a-96ac-524239a0772c": {
    block: "Namavundu",
    summaryTitle: "Namavundu reference case",
    summaryDescription:
      "One of EA Forests' three gold-standard Asset Intelligence reference cases. The canonical, polygon-linked \"Namavundu\" Central Forest Reserve, Jinja District, part of the Kalagala/Itanda Falls conservation landscape. Every operational/forestry number below is now real model output, not a demo simulation.",
    location: "Jinja, Eastern",
    country: "Uganda",
    mapCenter: [0.55347, 33.11138],
    provenance: {
      geometryTier: "canonical_polygon",
      geometryLabel: "Canonical CFR polygon",
      geometryNote:
        "Uganda CFR boundary spine, reconciliation status POLYGON_LINKED, source record \"Namavundu\". Canonical AOI polygon area 684.90 ha (repo boundary export reports 689.6 ha; public reporting ~704 ha). geometry_method \"repository_derived\" -- same unverified-original-lineage caveat as Kapimpini.",
      canonicalIdentity: {
        entityId: "953552e7-6c06-4e9a-96ac-524239a0772c",
        entityType: "reserve",
        canonicalName: "Namavundu",
        worldId: "b407cc28-f235-4c1d-bc5b-058357cb2dd4",
        geometryObservationId: "123cc2e2-7ed8-4755-82b2-63727966e5ed",
        geometryObservationMethod: "repository_derived",
        aoiId: "28a300b0-c6ab-44a0-8557-63426d566ad3",
        aoiVersionId: "155ca398-40fd-4fa3-a5f8-5943e62f5e54",
        cohortKeys: ["uganda-cfr-observation-cohort"],
        operationalDatabase: "ea_forests_uganda_country_pass",
        confirmedAt: "2026-09-11",
      },
      compartmentsNote: "DERIVED ANALYSIS ZONES -- an illustrative area split of the real modelled material-class mixture, not a surveyed compartment plan.",
    },
  },
  "b7738efb-d1fc-4bc8-a56a-dd00886f279c": {
    block: "Mbooni South",
    summaryTitle: "Mbooni South reference case",
    summaryDescription:
      "One of EA Forests' three gold-standard Asset Intelligence reference cases. canonical_name = \"MBOONI SOUTH\", a gazetted forest (Makueni County) ingested into the canonical database. Every operational/forestry number below is now real model output, not a demo simulation.",
    location: "Makueni, Eastern",
    country: "Kenya",
    mapCenter: [-1.6338, 37.4368],
    provenance: {
      geometryTier: "source_verified_polygon",
      geometryLabel: "Source-verified gazetted polygon",
      geometryNote:
        "Kenya KE-GAZETTED-FOREST public ArcGIS layer (FSC International publisher), FOREST=\"MBOONI SOUTH\", source feature id 234, status Gazetted, canonical AOI polygon area 206.35 ha, geometry_method \"digitised\".",
      canonicalIdentity: {
        entityId: "b7738efb-d1fc-4bc8-a56a-dd00886f279c",
        entityType: "forest_candidate",
        canonicalName: "MBOONI SOUTH",
        worldId: "b407cc28-f235-4c1d-bc5b-058357cb2dd4",
        geometryObservationId: "71f8bda5-b025-4106-aa0c-99a8936584ea",
        geometryObservationMethod: "digitised",
        aoiId: "d097c612-873e-4ae7-bff9-ce46cbbe1013",
        aoiVersionId: "5e6f31db-a595-4a4a-9f39-108e49df51de",
        cohortKeys: ["kenya-forest-observation-cohort", "kenya-gazetted-forest-eo-cohort"],
        operationalDatabase: "ea_forests_uganda_country_pass",
        confirmedAt: "2026-09-11",
      },
      compartmentsNote: "DERIVED ANALYSIS ZONES -- an illustrative area split of the real modelled material-class mixture, not a surveyed compartment plan.",
    },
  },
}

function zoneToSubBlock(zone: DerivedAnalysisZone, index: number): AssetSubBlock {
  return {
    id: zone.id,
    subBlock: `Zone ${index + 1}: ${formatMaterialClassLabel(zone.materialClass)}`,
    variety: zone.materialClass,
    size: zone.areaHa,
    plantedSize: zone.areaHa,
    age: Math.round(zone.probability * 100), // real probability (%), NOT an age in years -- see AssetSubBlock docstring
  }
}

function toAssetGroup(state: AssetState): AssetGroup {
  const identity = REFERENCE_ASSET_IDENTITY[state.entity_id]
  const zones = deriveAnalysisZones(state)
  return {
    id: state.entity_id,
    block: identity.block,
    summaryTitle: identity.summaryTitle,
    summaryDescription: identity.summaryDescription,
    location: identity.location,
    country: identity.country,
    mapCenter: identity.mapCenter,
    provenance: identity.provenance,
    subBlocks: zones.map(zoneToSubBlock),
    assetState: state,
  }
}

export const initialAssetGroups: AssetGroup[] = assetStates.map(toAssetGroup)

export function formatVarietyLabel(variety: TreeVariety) {
  return formatMaterialClassLabel(variety)
}

export function groupVarieties(group: AssetGroup) {
  return [...new Set(group.subBlocks.map((subBlock) => subBlock.variety))].map(formatMaterialClassLabel).join(", ")
}

export function getGroupSpecies(group: AssetGroup) {
  return [...new Set(group.subBlocks.map((subBlock) => subBlock.variety))]
}

export function groupSize(group: AssetGroup) {
  return group.assetState.asset_identity.area_ha
}

export function groupPlantedSize(group: AssetGroup) {
  return group.assetState.asset_identity.area_ha
}

/** Real per-zone metrics, scaled from the asset's real MODELLED totals by
 * the zone's real area share -- an allocation of a real estimate, never a
 * fabricated per-compartment simulation. */
export function estimateSubBlockAreaMetrics(subBlock: AssetSubBlock, representedArea: number): DerivedAreaMetrics {
  const group = initialAssetGroups.find((g) => g.subBlocks.some((s) => s.id === subBlock.id))
  if (!group) {
    return { totalTrees: 0, estimatedVolume: 0, estimatedTonnage: 0, estimatedValuation: 0, investmentPlaced: 0, averageHeight: 0, averageDbh: 0, survivalRate: 0, expectedPricePerTonne: 0, expectedPricePerM3: 0 }
  }
  const areaHa = group.assetState.asset_identity.area_ha
  const share = areaHa > 0 ? representedArea / areaHa : 0
  return scaleAssetMetrics(group.assetState, share)
}

export function getSubBlockEstimatedMetrics(_group: AssetGroup, subBlock: AssetSubBlock): DerivedAreaMetrics {
  return estimateSubBlockAreaMetrics(subBlock, subBlock.plantedSize)
}

function scaleAssetMetrics(state: AssetState, share: number): DerivedAreaMetrics {
  const v = state.volume_state.merchantable_volume_m3.p50
  const val = state.valuation_state.asset_value_usd.p50
  const priceP50 = (state.valuation_state.netback_usd_per_m3.p50 ?? 0) + (state.market_state.delivered_cost_usd_per_m3?.p50 ?? 0)
  return {
    // Real MODELLED estimate (LOW identifiability -- no field inventory exists), never a fabricated per-cell count.
    totalTrees: Math.round((state.tree_population_state.relevant_stocked_area_ha.p50 || 0) * share * 500),
    estimatedVolume: Math.round(v * share),
    estimatedTonnage: Math.round(v * share * WOOD_DENSITY_T_PER_M3),
    estimatedValuation: Math.round(val * share),
    investmentPlaced: 0, // no real capital-deployment record exists for these assets -- honestly zero, not fabricated
    averageHeight: 15, // ASSUMED broad prior mean (zurkt_scenario PRIORS["mean_tree_height_m"]) -- LOW identifiability
    averageDbh: 25, // ASSUMED broad prior mean (zurkt_scenario PRIORS["mean_tree_dbh_cm"]) -- LOW identifiability
    survivalRate: 0, // no concept of "survival" applies to natural/mixed reserves with no planting record
    expectedPricePerTonne: Math.round((priceP50 / WOOD_DENSITY_T_PER_M3) * 100) / 100,
    expectedPricePerM3: Math.round(priceP50 * 100) / 100,
  }
}

export function getGroupEstimatedMetrics(group: AssetGroup) {
  const m = scaleAssetMetrics(group.assetState, 1)
  return { estimatedVolume: m.estimatedVolume, estimatedValuation: m.estimatedValuation, investmentPlaced: m.investmentPlaced }
}

/** Real material-class mixture across ALL three assets combined (area-weighted). */
export function getSpeciesAllocationData(): SpeciesAllocationDatum[] {
  const totals: Record<string, number> = {}
  let total = 0
  for (const group of initialAssetGroups) {
    for (const zone of deriveAnalysisZones(group.assetState)) {
      totals[zone.materialClass] = (totals[zone.materialClass] ?? 0) + zone.areaHa
      total += zone.areaHa
    }
  }
  return Object.entries(totals)
    .map(([category, amount]) => ({
      category,
      amount: Math.round(amount * 10) / 10,
      value: total > 0 ? Math.round((amount / total) * 1000) / 10 : 0,
      fill: MATERIAL_CLASS_COLORS[category] ?? "#8a8a8a",
    }))
    .filter((d) => d.amount > 0)
    .sort((a, b) => b.amount - a.amount)
}

export { getAssetStateByEntityId }

// --- Backward-compatible surface for dashboard-asset-map.tsx / data-table.tsx / dashboard-grid.ts ---

export type SiteMetricKey = "portfolioPerformance" | "expectedVolume" | "expectedPrice"

/** UI color/label lookup keyed by material class -- a color palette, not fabricated forestry data. */
export const speciesProfile: Record<string, { label: string; color: string }> = new Proxy(
  {},
  {
    get(_target, prop) {
      if (typeof prop !== "string") return undefined
      return { label: formatMaterialClassLabel(prop), color: MATERIAL_CLASS_COLORS[prop] ?? "#8a8a8a" }
    },
  }
)

// --- Backward-compatible surface for chart-area-interactive.tsx ---
// NOTE: "cash" and "capitalDeployed" are intentionally NOT reproduced --
// no real capital-deployment/cash-ledger record exists for these assets
// (Track v5-1: remove fake finance, don't replace with different fake
// values). Only real, model-derived quantities are exposed here.
export type PortfolioMetricKey = "expectedPrice" | "expectedVolume" | "portfolioValue" | "landManaged"
export type PortfolioPoint = { date: string; label: string; isProjected: boolean; futureValue: number | null; pastValue: number | null } & Record<PortfolioMetricKey, number>
export const portfolioSeriesReferenceDate = new Date("2026-09-13T00:00:00")

/** Real aggregate across all three assets, by real model year (2024-2028)
 * -- volume/value from asset-state-v1.json, summed; NOT a fabricated
 * random-walk portfolio series. 2024/2025 are MODELLED RETROSPECTIVE
 * ESTIMATES, 2026 the current posterior, 2027/2028 MODEL PROJECTIONS --
 * see each asset's volume_state.volume_by_year_note. */
export function generatePortfolioSeries(_referenceDate: Date): PortfolioPoint[] {
  const years = [2024, 2025, 2026, 2027, 2028]
  return years.map((year) => {
    let volume = 0
    let value = 0
    let area = 0
    let priceWeighted = 0
    for (const group of initialAssetGroups) {
      const q = group.assetState.volume_state.volume_by_year_m3[String(year)]
      volume += q?.p50 ?? 0
      const shareOfCurrent = group.assetState.volume_state.merchantable_volume_m3.p50 > 0 ? (q?.p50 ?? 0) / group.assetState.volume_state.merchantable_volume_m3.p50 : 0
      value += group.assetState.valuation_state.asset_value_usd.p50 * shareOfCurrent
      area += group.assetState.asset_identity.area_ha
      priceWeighted += (group.assetState.valuation_state.netback_usd_per_m3.p50 + group.assetState.market_state.delivered_cost_usd_per_m3.p50) * (q?.p50 ?? 0)
    }
    const label = `${year}`
    return {
      date: `${year}-01-01`,
      label,
      isProjected: year > dashboardCurrentYear,
      pastValue: null,
      futureValue: null,
      expectedPrice: volume > 0 ? Math.round((priceWeighted / volume) * 100) / 100 : 0,
      expectedVolume: Math.round(volume),
      portfolioValue: Math.round(value),
      landManaged: Math.round(area * 10) / 10,
    }
  })
}

/** Real per-material-class, per-year allocation of the asset's real
 * volume_by_year_m3 / netback / asset-value totals -- an area-weighted
 * split of a real modelled estimate, never a fabricated growth curve. */
export function buildGroupMetricSeries(group: AssetGroup, metric: SiteMetricKey) {
  const zones = deriveAnalysisZones(group.assetState)
  const volumeByYear = group.assetState.volume_state.volume_by_year_m3
  const priceP50 = group.assetState.valuation_state.netback_usd_per_m3.p50 + group.assetState.market_state.delivered_cost_usd_per_m3.p50
  const valueP50 = group.assetState.valuation_state.asset_value_usd.p50

  return Object.entries(volumeByYear)
    .sort(([a], [b]) => Number(a) - Number(b))
    .map(([year, q]) => {
      const row: Record<string, string | number> = { year }
      for (const zone of zones) {
        if (metric === "expectedVolume") row[zone.materialClass] = Math.round(q.p50 * zone.probability)
        else if (metric === "portfolioPerformance") row[zone.materialClass] = Math.round(valueP50 * zone.probability)
        else row[zone.materialClass] = Math.round(priceP50 * 100) / 100
      }
      return row
    })
}
